% -------------------------------------------------------------------
%  Generated by MATLAB on 22-Jan-2021 16:11:08
%  MATLAB version: 9.8.0.1451342 (R2020a) Update 5
% -------------------------------------------------------------------
saveVarsMat = load('CasevvlqFlatL1pi.mat');

value = saveVarsMat.value; % <1x1 shape_solveh> unsupported class

clear saveVarsMat;
